//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextMiner.SentenceSplitter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.fulltextwebservices/", ConfigurationName="SentenceSplitter.SentenceSplitter")]
    public interface SentenceSplitter {
        
        // CODEGEN: Parameter 'sentencesArray' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sentencesArray")]
        TextMiner.SentenceSplitter.splitIntoSentencesResponse splitIntoSentences(TextMiner.SentenceSplitter.splitIntoSentencesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="splitIntoSentences", WrapperNamespace="http://webservices.fulltextwebservices/", IsWrapped=true)]
    public partial class splitIntoSentencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.fulltextwebservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string textToSplit;
        
        public splitIntoSentencesRequest() {
        }
        
        public splitIntoSentencesRequest(string textToSplit) {
            this.textToSplit = textToSplit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="splitIntoSentencesResponse", WrapperNamespace="http://webservices.fulltextwebservices/", IsWrapped=true)]
    public partial class splitIntoSentencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.fulltextwebservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sentencesArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] sentencesArray;
        
        public splitIntoSentencesResponse() {
        }
        
        public splitIntoSentencesResponse(string[] sentencesArray) {
            this.sentencesArray = sentencesArray;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SentenceSplitterChannel : TextMiner.SentenceSplitter.SentenceSplitter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SentenceSplitterClient : System.ServiceModel.ClientBase<TextMiner.SentenceSplitter.SentenceSplitter>, TextMiner.SentenceSplitter.SentenceSplitter {
        
        public SentenceSplitterClient() {
        }
        
        public SentenceSplitterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SentenceSplitterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SentenceSplitterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SentenceSplitterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextMiner.SentenceSplitter.splitIntoSentencesResponse TextMiner.SentenceSplitter.SentenceSplitter.splitIntoSentences(TextMiner.SentenceSplitter.splitIntoSentencesRequest request) {
            return base.Channel.splitIntoSentences(request);
        }
        
        public string[] splitIntoSentences(string textToSplit) {
            TextMiner.SentenceSplitter.splitIntoSentencesRequest inValue = new TextMiner.SentenceSplitter.splitIntoSentencesRequest();
            inValue.textToSplit = textToSplit;
            TextMiner.SentenceSplitter.splitIntoSentencesResponse retVal = ((TextMiner.SentenceSplitter.SentenceSplitter)(this)).splitIntoSentences(inValue);
            return retVal.sentencesArray;
        }
    }
}
