//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace TextMiner.ProviderSchema.ClinicalTrialsGov.ClinicalStudy
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class clinical_study {
        
        private required_header required_headerField;
        
        private id_info id_infoField;
        
        private string brief_titleField;
        
        private string acronymField;
        
        private string official_titleField;
        
        private sponsors sponsorsField;
        
        private string sourceField;
        
        private oversight_info oversight_infoField;
        
        private brief_summary brief_summaryField;
        
        private detailed_description detailed_descriptionField;
        
        private string overall_statusField;
        
        private string why_stoppedField;
        
        private string start_dateField;
        
        private completion_date completion_dateField;
        
        private primary_completion_date primary_completion_dateField;
        
        private string phaseField;
        
        private string study_typeField;
        
        private string study_designField;
        
        private primary_outcome[] primary_outcomeField;
        
        private secondary_outcome[] secondary_outcomeField;
        
        private string number_of_armsField;
        
        private string number_of_groupsField;
        
        private enrollment enrollmentField;
        
        private string[] conditionField;
        
        private arm_group[] arm_groupField;
        
        private intervention[] interventionField;
        
        private string biospec_retentionField;
        
        private biospec_descr biospec_descrField;
        
        private eligibility eligibilityField;
        
        private overall_official[] overall_officialField;
        
        private overall_contact overall_contactField;
        
        private overall_contact_backup overall_contact_backupField;
        
        private location[] locationField;
        
        private link[] linkField;
        
        private reference[] referenceField;
        
        private results_reference[] results_referenceField;
        
        private string verification_dateField;
        
        private string lastchanged_dateField;
        
        private string firstreceived_dateField;
        
        private responsible_party responsible_partyField;
        
        private string rankField;
        
        public clinical_study() {
            this.rankField = "0";
        }
        
        /// <remarks/>
        public required_header required_header {
            get {
                return this.required_headerField;
            }
            set {
                this.required_headerField = value;
            }
        }
        
        /// <remarks/>
        public id_info id_info {
            get {
                return this.id_infoField;
            }
            set {
                this.id_infoField = value;
            }
        }
        
        /// <remarks/>
        public string brief_title {
            get {
                return this.brief_titleField;
            }
            set {
                this.brief_titleField = value;
            }
        }
        
        /// <remarks/>
        public string acronym {
            get {
                return this.acronymField;
            }
            set {
                this.acronymField = value;
            }
        }
        
        /// <remarks/>
        public string official_title {
            get {
                return this.official_titleField;
            }
            set {
                this.official_titleField = value;
            }
        }
        
        /// <remarks/>
        public sponsors sponsors {
            get {
                return this.sponsorsField;
            }
            set {
                this.sponsorsField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public oversight_info oversight_info {
            get {
                return this.oversight_infoField;
            }
            set {
                this.oversight_infoField = value;
            }
        }
        
        /// <remarks/>
        public brief_summary brief_summary {
            get {
                return this.brief_summaryField;
            }
            set {
                this.brief_summaryField = value;
            }
        }
        
        /// <remarks/>
        public detailed_description detailed_description {
            get {
                return this.detailed_descriptionField;
            }
            set {
                this.detailed_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string overall_status {
            get {
                return this.overall_statusField;
            }
            set {
                this.overall_statusField = value;
            }
        }
        
        /// <remarks/>
        public string why_stopped {
            get {
                return this.why_stoppedField;
            }
            set {
                this.why_stoppedField = value;
            }
        }
        
        /// <remarks/>
        public string start_date {
            get {
                return this.start_dateField;
            }
            set {
                this.start_dateField = value;
            }
        }
        
        /// <remarks/>
        public completion_date completion_date {
            get {
                return this.completion_dateField;
            }
            set {
                this.completion_dateField = value;
            }
        }
        
        /// <remarks/>
        public primary_completion_date primary_completion_date {
            get {
                return this.primary_completion_dateField;
            }
            set {
                this.primary_completion_dateField = value;
            }
        }
        
        /// <remarks/>
        public string phase {
            get {
                return this.phaseField;
            }
            set {
                this.phaseField = value;
            }
        }
        
        /// <remarks/>
        public string study_type {
            get {
                return this.study_typeField;
            }
            set {
                this.study_typeField = value;
            }
        }
        
        /// <remarks/>
        public string study_design {
            get {
                return this.study_designField;
            }
            set {
                this.study_designField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("primary_outcome")]
        public primary_outcome[] primary_outcome {
            get {
                return this.primary_outcomeField;
            }
            set {
                this.primary_outcomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("secondary_outcome")]
        public secondary_outcome[] secondary_outcome {
            get {
                return this.secondary_outcomeField;
            }
            set {
                this.secondary_outcomeField = value;
            }
        }
        
        /// <remarks/>
        public string number_of_arms {
            get {
                return this.number_of_armsField;
            }
            set {
                this.number_of_armsField = value;
            }
        }
        
        /// <remarks/>
        public string number_of_groups {
            get {
                return this.number_of_groupsField;
            }
            set {
                this.number_of_groupsField = value;
            }
        }
        
        /// <remarks/>
        public enrollment enrollment {
            get {
                return this.enrollmentField;
            }
            set {
                this.enrollmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condition")]
        public string[] condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arm_group")]
        public arm_group[] arm_group {
            get {
                return this.arm_groupField;
            }
            set {
                this.arm_groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("intervention")]
        public intervention[] intervention {
            get {
                return this.interventionField;
            }
            set {
                this.interventionField = value;
            }
        }
        
        /// <remarks/>
        public string biospec_retention {
            get {
                return this.biospec_retentionField;
            }
            set {
                this.biospec_retentionField = value;
            }
        }
        
        /// <remarks/>
        public biospec_descr biospec_descr {
            get {
                return this.biospec_descrField;
            }
            set {
                this.biospec_descrField = value;
            }
        }
        
        /// <remarks/>
        public eligibility eligibility {
            get {
                return this.eligibilityField;
            }
            set {
                this.eligibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("overall_official")]
        public overall_official[] overall_official {
            get {
                return this.overall_officialField;
            }
            set {
                this.overall_officialField = value;
            }
        }
        
        /// <remarks/>
        public overall_contact overall_contact {
            get {
                return this.overall_contactField;
            }
            set {
                this.overall_contactField = value;
            }
        }
        
        /// <remarks/>
        public overall_contact_backup overall_contact_backup {
            get {
                return this.overall_contact_backupField;
            }
            set {
                this.overall_contact_backupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("location")]
        public location[] location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reference")]
        public reference[] reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("results_reference")]
        public results_reference[] results_reference {
            get {
                return this.results_referenceField;
            }
            set {
                this.results_referenceField = value;
            }
        }
        
        /// <remarks/>
        public string verification_date {
            get {
                return this.verification_dateField;
            }
            set {
                this.verification_dateField = value;
            }
        }
        
        /// <remarks/>
        public string lastchanged_date {
            get {
                return this.lastchanged_dateField;
            }
            set {
                this.lastchanged_dateField = value;
            }
        }
        
        /// <remarks/>
        public string firstreceived_date {
            get {
                return this.firstreceived_dateField;
            }
            set {
                this.firstreceived_dateField = value;
            }
        }
        
        /// <remarks/>
        public responsible_party responsible_party {
            get {
                return this.responsible_partyField;
            }
            set {
                this.responsible_partyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class required_header {
        
        private string download_dateField;
        
        private string link_textField;
        
        private string urlField;
        
        /// <remarks/>
        public string download_date {
            get {
                return this.download_dateField;
            }
            set {
                this.download_dateField = value;
            }
        }
        
        /// <remarks/>
        public string link_text {
            get {
                return this.link_textField;
            }
            set {
                this.link_textField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class id_info {
        
        private string org_study_idField;
        
        private string[] secondary_idField;
        
        private string nct_idField;
        
        private string[] nct_aliasField;
        
        /// <remarks/>
        public string org_study_id {
            get {
                return this.org_study_idField;
            }
            set {
                this.org_study_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("secondary_id")]
        public string[] secondary_id {
            get {
                return this.secondary_idField;
            }
            set {
                this.secondary_idField = value;
            }
        }
        
        /// <remarks/>
        public string nct_id {
            get {
                return this.nct_idField;
            }
            set {
                this.nct_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nct_alias")]
        public string[] nct_alias {
            get {
                return this.nct_aliasField;
            }
            set {
                this.nct_aliasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class sponsors {
        
        private lead_sponsor lead_sponsorField;
        
        private collaborator[] collaboratorField;
        
        /// <remarks/>
        public lead_sponsor lead_sponsor {
            get {
                return this.lead_sponsorField;
            }
            set {
                this.lead_sponsorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("collaborator")]
        public collaborator[] collaborator {
            get {
                return this.collaboratorField;
            }
            set {
                this.collaboratorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class lead_sponsor {
        
        private string agencyField;
        
        /// <remarks/>
        public string agency {
            get {
                return this.agencyField;
            }
            set {
                this.agencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class collaborator {
        
        private string agencyField;
        
        /// <remarks/>
        public string agency {
            get {
                return this.agencyField;
            }
            set {
                this.agencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class oversight_info {
        
        private string[] authorityField;
        
        private string has_dmcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authority")]
        public string[] authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string has_dmc {
            get {
                return this.has_dmcField;
            }
            set {
                this.has_dmcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class brief_summary {
        
        private string textblockField;
        
        /// <remarks/>
        public string textblock {
            get {
                return this.textblockField;
            }
            set {
                this.textblockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class detailed_description {
        
        private string textblockField;
        
        /// <remarks/>
        public string textblock {
            get {
                return this.textblockField;
            }
            set {
                this.textblockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class completion_date {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class primary_completion_date {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class primary_outcome {
        
        private string measureField;
        
        private string time_frameField;
        
        private string safety_issueField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string measure {
            get {
                return this.measureField;
            }
            set {
                this.measureField = value;
            }
        }
        
        /// <remarks/>
        public string time_frame {
            get {
                return this.time_frameField;
            }
            set {
                this.time_frameField = value;
            }
        }
        
        /// <remarks/>
        public string safety_issue {
            get {
                return this.safety_issueField;
            }
            set {
                this.safety_issueField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class secondary_outcome {
        
        private string measureField;
        
        private string time_frameField;
        
        private string safety_issueField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string measure {
            get {
                return this.measureField;
            }
            set {
                this.measureField = value;
            }
        }
        
        /// <remarks/>
        public string time_frame {
            get {
                return this.time_frameField;
            }
            set {
                this.time_frameField = value;
            }
        }
        
        /// <remarks/>
        public string safety_issue {
            get {
                return this.safety_issueField;
            }
            set {
                this.safety_issueField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class enrollment {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class arm_group {
        
        private string arm_group_labelField;
        
        private string arm_group_typeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string arm_group_label {
            get {
                return this.arm_group_labelField;
            }
            set {
                this.arm_group_labelField = value;
            }
        }
        
        /// <remarks/>
        public string arm_group_type {
            get {
                return this.arm_group_typeField;
            }
            set {
                this.arm_group_typeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class intervention {
        
        private string intervention_typeField;
        
        private string intervention_nameField;
        
        private string descriptionField;
        
        private string[] arm_group_labelField;
        
        private string[] other_nameField;
        
        /// <remarks/>
        public string intervention_type {
            get {
                return this.intervention_typeField;
            }
            set {
                this.intervention_typeField = value;
            }
        }
        
        /// <remarks/>
        public string intervention_name {
            get {
                return this.intervention_nameField;
            }
            set {
                this.intervention_nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arm_group_label")]
        public string[] arm_group_label {
            get {
                return this.arm_group_labelField;
            }
            set {
                this.arm_group_labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("other_name")]
        public string[] other_name {
            get {
                return this.other_nameField;
            }
            set {
                this.other_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class biospec_descr {
        
        private string textblockField;
        
        /// <remarks/>
        public string textblock {
            get {
                return this.textblockField;
            }
            set {
                this.textblockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class eligibility {
        
        private study_pop study_popField;
        
        private string sampling_methodField;
        
        private criteria criteriaField;
        
        private string genderField;
        
        private string minimum_ageField;
        
        private string maximum_ageField;
        
        private string healthy_volunteersField;
        
        /// <remarks/>
        public study_pop study_pop {
            get {
                return this.study_popField;
            }
            set {
                this.study_popField = value;
            }
        }
        
        /// <remarks/>
        public string sampling_method {
            get {
                return this.sampling_methodField;
            }
            set {
                this.sampling_methodField = value;
            }
        }
        
        /// <remarks/>
        public criteria criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
        
        /// <remarks/>
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string minimum_age {
            get {
                return this.minimum_ageField;
            }
            set {
                this.minimum_ageField = value;
            }
        }
        
        /// <remarks/>
        public string maximum_age {
            get {
                return this.maximum_ageField;
            }
            set {
                this.maximum_ageField = value;
            }
        }
        
        /// <remarks/>
        public string healthy_volunteers {
            get {
                return this.healthy_volunteersField;
            }
            set {
                this.healthy_volunteersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class study_pop {
        
        private string textblockField;
        
        /// <remarks/>
        public string textblock {
            get {
                return this.textblockField;
            }
            set {
                this.textblockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class criteria {
        
        private string textblockField;
        
        /// <remarks/>
        public string textblock {
            get {
                return this.textblockField;
            }
            set {
                this.textblockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class overall_official {
        
        private string last_nameField;
        
        private string roleField;
        
        private string affiliationField;
        
        /// <remarks/>
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public string affiliation {
            get {
                return this.affiliationField;
            }
            set {
                this.affiliationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class overall_contact {
        
        private string last_nameField;
        
        private string phoneField;
        
        private string phone_extField;
        
        private string emailField;
        
        /// <remarks/>
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string phone_ext {
            get {
                return this.phone_extField;
            }
            set {
                this.phone_extField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class overall_contact_backup {
        
        private string last_nameField;
        
        private string phoneField;
        
        private string phone_extField;
        
        private string emailField;
        
        /// <remarks/>
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string phone_ext {
            get {
                return this.phone_extField;
            }
            set {
                this.phone_extField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class location {
        
        private facility facilityField;
        
        private string statusField;
        
        private contact contactField;
        
        private contact_backup contact_backupField;
        
        private investigator[] investigatorField;
        
        /// <remarks/>
        public facility facility {
            get {
                return this.facilityField;
            }
            set {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public contact contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public contact_backup contact_backup {
            get {
                return this.contact_backupField;
            }
            set {
                this.contact_backupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("investigator")]
        public investigator[] investigator {
            get {
                return this.investigatorField;
            }
            set {
                this.investigatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class facility {
        
        private string nameField;
        
        private address addressField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class address {
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string countryField;
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class contact {
        
        private string last_nameField;
        
        private string phoneField;
        
        private string phone_extField;
        
        private string emailField;
        
        /// <remarks/>
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string phone_ext {
            get {
                return this.phone_extField;
            }
            set {
                this.phone_extField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class contact_backup {
        
        private string last_nameField;
        
        private string phoneField;
        
        private string phone_extField;
        
        private string emailField;
        
        /// <remarks/>
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string phone_ext {
            get {
                return this.phone_extField;
            }
            set {
                this.phone_extField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class investigator {
        
        private string last_nameField;
        
        private string roleField;
        
        /// <remarks/>
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class link {
        
        private string urlField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class reference {
        
        private string citationField;
        
        private string pMIDField;
        
        /// <remarks/>
        public string citation {
            get {
                return this.citationField;
            }
            set {
                this.citationField = value;
            }
        }
        
        /// <remarks/>
        public string PMID {
            get {
                return this.pMIDField;
            }
            set {
                this.pMIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class results_reference {
        
        private string citationField;
        
        private string pMIDField;
        
        /// <remarks/>
        public string citation {
            get {
                return this.citationField;
            }
            set {
                this.citationField = value;
            }
        }
        
        /// <remarks/>
        public string PMID {
            get {
                return this.pMIDField;
            }
            set {
                this.pMIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClinicalTrialsGovClinicalStudy", IsNullable=false)]
    public partial class responsible_party {
        
        private string name_titleField;
        
        private string organizationField;
        
        /// <remarks/>
        public string name_title {
            get {
                return this.name_titleField;
            }
            set {
                this.name_titleField = value;
            }
        }
        
        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
    }
}
