//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace TextMiner.ProviderSchema.Pubget {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Pubget")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Pubget", IsNullable=false)]
    public partial class articles {
        
        private articlesArticle[] articleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("article")]
        public articlesArticle[] article {
            get {
                return this.articleField;
            }
            set {
                this.articleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Pubget")]
    public partial class articlesArticle {
        
        private int idField;
        
        private string titleField;
        
        private string[] authorsField;
        
        private string abstractField;
        
        private string journalField;
        
        private string issnField;
        
        private int volumeField;
        
        private int issueField;
        
        private int start_pageField;
        
        private int end_pageField;
        
        private string dateField;
        
        private string languageField;
        
        private string[] mesh_termsField;
        
        private string htmlField;
        
        private string pdfField;
        
        private string find_itField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("author", IsNullable=false)]
        public string[] authors {
            get {
                return this.authorsField;
            }
            set {
                this.authorsField = value;
            }
        }
        
        /// <remarks/>
        public string @abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
            }
        }
        
        /// <remarks/>
        public string journal {
            get {
                return this.journalField;
            }
            set {
                this.journalField = value;
            }
        }
        
        /// <remarks/>
        public string issn {
            get {
                return this.issnField;
            }
            set {
                this.issnField = value;
            }
        }
        
        /// <remarks/>
        public int volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        public int issue {
            get {
                return this.issueField;
            }
            set {
                this.issueField = value;
            }
        }
        
        /// <remarks/>
        public int start_page {
            get {
                return this.start_pageField;
            }
            set {
                this.start_pageField = value;
            }
        }
        
        /// <remarks/>
        public int end_page {
            get {
                return this.end_pageField;
            }
            set {
                this.end_pageField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mesh_term", IsNullable=false)]
        public string[] mesh_terms {
            get {
                return this.mesh_termsField;
            }
            set {
                this.mesh_termsField = value;
            }
        }
        
        /// <remarks/>
        public string html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
            }
        }
        
        /// <remarks/>
        public string pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        public string find_it {
            get {
                return this.find_itField;
            }
            set {
                this.find_itField = value;
            }
        }
    }
}
