//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace TextMiner.ProviderSchema.PubMed.Search {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PubMedSearch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PubMedSearch", IsNullable=false)]
    public partial class IdList {
        
        private string[] idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Id")]
        public string[] Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PubMedSearch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PubMedSearch", IsNullable=false)]
    public partial class Translation {
        
        private string fromField;
        
        private string toField;
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PubMedSearch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PubMedSearch", IsNullable=false)]
    public partial class TranslationSet {
        
        private Translation[] translationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Translation")]
        public Translation[] Translation {
            get {
                return this.translationField;
            }
            set {
                this.translationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PubMedSearch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PubMedSearch", IsNullable=false)]
    public partial class TermSet {
        
        private string termField;
        
        private string fieldField;
        
        private string countField;
        
        private string explodeField;
        
        /// <remarks/>
        public string Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string Explode {
            get {
                return this.explodeField;
            }
            set {
                this.explodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PubMedSearch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PubMedSearch", IsNullable=false)]
    public partial class TranslationStack {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OP", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TermSet", typeof(TermSet))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PubMedSearch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PubMedSearch", IsNullable=false)]
    public partial class ErrorList {
        
        private string[] phraseNotFoundField;
        
        private string[] fieldNotFoundField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhraseNotFound")]
        public string[] PhraseNotFound {
            get {
                return this.phraseNotFoundField;
            }
            set {
                this.phraseNotFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FieldNotFound")]
        public string[] FieldNotFound {
            get {
                return this.fieldNotFoundField;
            }
            set {
                this.fieldNotFoundField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PubMedSearch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PubMedSearch", IsNullable=false)]
    public partial class WarningList {
        
        private string[] phraseIgnoredField;
        
        private string[] quotedPhraseNotFoundField;
        
        private string[] outputMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhraseIgnored")]
        public string[] PhraseIgnored {
            get {
                return this.phraseIgnoredField;
            }
            set {
                this.phraseIgnoredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QuotedPhraseNotFound")]
        public string[] QuotedPhraseNotFound {
            get {
                return this.quotedPhraseNotFoundField;
            }
            set {
                this.quotedPhraseNotFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OutputMessage")]
        public string[] OutputMessage {
            get {
                return this.outputMessageField;
            }
            set {
                this.outputMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PubMedSearch")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PubMedSearch", IsNullable=false)]
    public partial class eSearchResult {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private ErrorList errorListField;
        
        private WarningList warningListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Count", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ERROR", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("IdList", typeof(IdList))]
        [System.Xml.Serialization.XmlElementAttribute("QueryKey", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("QueryTranslation", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("RetMax", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("RetStart", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TranslationSet", typeof(TranslationSet))]
        [System.Xml.Serialization.XmlElementAttribute("TranslationStack", typeof(TranslationStack))]
        [System.Xml.Serialization.XmlElementAttribute("WebEnv", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        public ErrorList ErrorList {
            get {
                return this.errorListField;
            }
            set {
                this.errorListField = value;
            }
        }
        
        /// <remarks/>
        public WarningList WarningList {
            get {
                return this.warningListField;
            }
            set {
                this.warningListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/PubMedSearch", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Count,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        IdList,
        
        /// <remarks/>
        QueryKey,
        
        /// <remarks/>
        QueryTranslation,
        
        /// <remarks/>
        RetMax,
        
        /// <remarks/>
        RetStart,
        
        /// <remarks/>
        TranslationSet,
        
        /// <remarks/>
        TranslationStack,
        
        /// <remarks/>
        WebEnv,
    }
}
