//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace TextMiner.ProviderSchema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Terminizer")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Terminizer", IsNullable=false)]
    public partial class TerminizerResult {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cruft", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MatchedTermList", typeof(MatchedTermList))]
        [System.Xml.Serialization.XmlElementAttribute("OntologyMatches", typeof(TerminizerResultOntologyMatches))]
        [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Terminizer")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Terminizer", IsNullable=false)]
    public partial class MatchedTermList {
        
        private MatchedTermListMatchedTerm[] matchedTermField;
        
        private int indexField;
        
        private bool indexFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MatchedTerm")]
        public MatchedTermListMatchedTerm[] MatchedTerm {
            get {
                return this.matchedTermField;
            }
            set {
                this.matchedTermField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indexSpecified {
            get {
                return this.indexFieldSpecified;
            }
            set {
                this.indexFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Terminizer")]
    public partial class MatchedTermListMatchedTerm {
        
        private string tokenIndicesField;
        
        private string omixedItemIDField;
        
        private string accessionField;
        
        private string definitionField;
        
        /// <remarks/>
        public string TokenIndices {
            get {
                return this.tokenIndicesField;
            }
            set {
                this.tokenIndicesField = value;
            }
        }
        
        /// <remarks/>
        public string OmixedItemID {
            get {
                return this.omixedItemIDField;
            }
            set {
                this.omixedItemIDField = value;
            }
        }
        
        /// <remarks/>
        public string Accession {
            get {
                return this.accessionField;
            }
            set {
                this.accessionField = value;
            }
        }
        
        /// <remarks/>
        public string Definition {
            get {
                return this.definitionField;
            }
            set {
                this.definitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Terminizer")]
    public partial class TerminizerResultOntologyMatches {
        
        private Ontology[] ontologyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ontology", IsNullable=true)]
        public Ontology[] Ontology {
            get {
                return this.ontologyField;
            }
            set {
                this.ontologyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Terminizer")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Terminizer", IsNullable=true)]
    public partial class Ontology {
        
        private string longNameField;
        
        private string shortNameField;
        
        private int hitsField;
        
        private bool hitsFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string longName {
            get {
                return this.longNameField;
            }
            set {
                this.longNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int hits {
            get {
                return this.hitsField;
            }
            set {
                this.hitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hitsSpecified {
            get {
                return this.hitsFieldSpecified;
            }
            set {
                this.hitsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Terminizer")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Terminizer", IsNullable=false)]
    public partial class Token {
        
        private string rawTextField;
        
        private int indexField;
        
        private bool indexFieldSpecified;
        
        /// <remarks/>
        public string RawText {
            get {
                return this.rawTextField;
            }
            set {
                this.rawTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indexSpecified {
            get {
                return this.indexFieldSpecified;
            }
            set {
                this.indexFieldSpecified = value;
            }
        }
    }
}
