//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextMiner.PdfToText {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.fulltextwebservices/", ConfigurationName="PdfToText.PdfToText")]
    public interface PdfToText {
        
        // CODEGEN: Generating message contract since element name pdfFileBase64 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TextMiner.PdfToText.pdfToTextBase64Response pdfToTextBase64(TextMiner.PdfToText.pdfToTextBase64Request request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://webservices.fulltextwebservices/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="extractedText")]
        TextMiner.PdfToText.pdfToTextResponse pdfToText(TextMiner.PdfToText.pdfToTextRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pdfToTextBase64Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pdfToTextBase64", Namespace="http://webservices.fulltextwebservices/", Order=0)]
        public TextMiner.PdfToText.pdfToTextBase64RequestBody Body;
        
        public pdfToTextBase64Request() {
        }
        
        public pdfToTextBase64Request(TextMiner.PdfToText.pdfToTextBase64RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pdfToTextBase64RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pdfFileBase64;
        
        public pdfToTextBase64RequestBody() {
        }
        
        public pdfToTextBase64RequestBody(string pdfFileBase64) {
            this.pdfFileBase64 = pdfFileBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pdfToTextBase64Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pdfToTextBase64Response", Namespace="http://webservices.fulltextwebservices/", Order=0)]
        public TextMiner.PdfToText.pdfToTextBase64ResponseBody Body;
        
        public pdfToTextBase64Response() {
        }
        
        public pdfToTextBase64Response(TextMiner.PdfToText.pdfToTextBase64ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pdfToTextBase64ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string extractedTextBase64;
        
        public pdfToTextBase64ResponseBody() {
        }
        
        public pdfToTextBase64ResponseBody(string extractedTextBase64) {
            this.extractedTextBase64 = extractedTextBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pdfToText", WrapperNamespace="http://webservices.fulltextwebservices/", IsWrapped=true)]
    public partial class pdfToTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] pdfFile;
        
        public pdfToTextRequest() {
        }
        
        public pdfToTextRequest(byte[] pdfFile) {
            this.pdfFile = pdfFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pdfToTextResponse", WrapperNamespace="http://webservices.fulltextwebservices/", IsWrapped=true)]
    public partial class pdfToTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] extractedText;
        
        public pdfToTextResponse() {
        }
        
        public pdfToTextResponse(byte[] extractedText) {
            this.extractedText = extractedText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PdfToTextChannel : TextMiner.PdfToText.PdfToText, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PdfToTextClient : System.ServiceModel.ClientBase<TextMiner.PdfToText.PdfToText>, TextMiner.PdfToText.PdfToText {
        
        public PdfToTextClient() {
        }
        
        public PdfToTextClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PdfToTextClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfToTextClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfToTextClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextMiner.PdfToText.pdfToTextBase64Response TextMiner.PdfToText.PdfToText.pdfToTextBase64(TextMiner.PdfToText.pdfToTextBase64Request request) {
            return base.Channel.pdfToTextBase64(request);
        }
        
        public string pdfToTextBase64(string pdfFileBase64) {
            TextMiner.PdfToText.pdfToTextBase64Request inValue = new TextMiner.PdfToText.pdfToTextBase64Request();
            inValue.Body = new TextMiner.PdfToText.pdfToTextBase64RequestBody();
            inValue.Body.pdfFileBase64 = pdfFileBase64;
            TextMiner.PdfToText.pdfToTextBase64Response retVal = ((TextMiner.PdfToText.PdfToText)(this)).pdfToTextBase64(inValue);
            return retVal.Body.extractedTextBase64;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextMiner.PdfToText.pdfToTextResponse TextMiner.PdfToText.PdfToText.pdfToText(TextMiner.PdfToText.pdfToTextRequest request) {
            return base.Channel.pdfToText(request);
        }
        
        public byte[] pdfToText(byte[] pdfFile) {
            TextMiner.PdfToText.pdfToTextRequest inValue = new TextMiner.PdfToText.pdfToTextRequest();
            inValue.pdfFile = pdfFile;
            TextMiner.PdfToText.pdfToTextResponse retVal = ((TextMiner.PdfToText.PdfToText)(this)).pdfToText(inValue);
            return retVal.extractedText;
        }
    }
}
