//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextMiner.TextCleaner {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.fulltextwebservices/", ConfigurationName="TextCleaner.TextCleaner")]
    public interface TextCleaner {
        
        // CODEGEN: Generating message contract since element name cleanedText from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TextMiner.TextCleaner.cleanTextResponse cleanText(TextMiner.TextCleaner.cleanTextRequest request);
        
        // CODEGEN: Generating message contract since element name cleanedTextASCII from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TextMiner.TextCleaner.cleanTextASCIIResponse cleanTextASCII(TextMiner.TextCleaner.cleanTextASCIIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cleanTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cleanText", Namespace="http://webservices.fulltextwebservices/", Order=0)]
        public TextMiner.TextCleaner.cleanTextRequestBody Body;
        
        public cleanTextRequest() {
        }
        
        public cleanTextRequest(TextMiner.TextCleaner.cleanTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cleanTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] textStringBytesUTF8;
        
        public cleanTextRequestBody() {
        }
        
        public cleanTextRequestBody(byte[] textStringBytesUTF8) {
            this.textStringBytesUTF8 = textStringBytesUTF8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cleanTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cleanTextResponse", Namespace="http://webservices.fulltextwebservices/", Order=0)]
        public TextMiner.TextCleaner.cleanTextResponseBody Body;
        
        public cleanTextResponse() {
        }
        
        public cleanTextResponse(TextMiner.TextCleaner.cleanTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cleanTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cleanedText;
        
        public cleanTextResponseBody() {
        }
        
        public cleanTextResponseBody(string cleanedText) {
            this.cleanedText = cleanedText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cleanTextASCIIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cleanTextASCII", Namespace="http://webservices.fulltextwebservices/", Order=0)]
        public TextMiner.TextCleaner.cleanTextASCIIRequestBody Body;
        
        public cleanTextASCIIRequest() {
        }
        
        public cleanTextASCIIRequest(TextMiner.TextCleaner.cleanTextASCIIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cleanTextASCIIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] textStringBytesUTF8;
        
        public cleanTextASCIIRequestBody() {
        }
        
        public cleanTextASCIIRequestBody(byte[] textStringBytesUTF8) {
            this.textStringBytesUTF8 = textStringBytesUTF8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cleanTextASCIIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cleanTextASCIIResponse", Namespace="http://webservices.fulltextwebservices/", Order=0)]
        public TextMiner.TextCleaner.cleanTextASCIIResponseBody Body;
        
        public cleanTextASCIIResponse() {
        }
        
        public cleanTextASCIIResponse(TextMiner.TextCleaner.cleanTextASCIIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cleanTextASCIIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cleanedTextASCII;
        
        public cleanTextASCIIResponseBody() {
        }
        
        public cleanTextASCIIResponseBody(string cleanedTextASCII) {
            this.cleanedTextASCII = cleanedTextASCII;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TextCleanerChannel : TextMiner.TextCleaner.TextCleaner, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TextCleanerClient : System.ServiceModel.ClientBase<TextMiner.TextCleaner.TextCleaner>, TextMiner.TextCleaner.TextCleaner {
        
        public TextCleanerClient() {
        }
        
        public TextCleanerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextCleanerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextCleanerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextCleanerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextMiner.TextCleaner.cleanTextResponse TextMiner.TextCleaner.TextCleaner.cleanText(TextMiner.TextCleaner.cleanTextRequest request) {
            return base.Channel.cleanText(request);
        }
        
        public string cleanText(byte[] textStringBytesUTF8) {
            TextMiner.TextCleaner.cleanTextRequest inValue = new TextMiner.TextCleaner.cleanTextRequest();
            inValue.Body = new TextMiner.TextCleaner.cleanTextRequestBody();
            inValue.Body.textStringBytesUTF8 = textStringBytesUTF8;
            TextMiner.TextCleaner.cleanTextResponse retVal = ((TextMiner.TextCleaner.TextCleaner)(this)).cleanText(inValue);
            return retVal.Body.cleanedText;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextMiner.TextCleaner.cleanTextASCIIResponse TextMiner.TextCleaner.TextCleaner.cleanTextASCII(TextMiner.TextCleaner.cleanTextASCIIRequest request) {
            return base.Channel.cleanTextASCII(request);
        }
        
        public string cleanTextASCII(byte[] textStringBytesUTF8) {
            TextMiner.TextCleaner.cleanTextASCIIRequest inValue = new TextMiner.TextCleaner.cleanTextASCIIRequest();
            inValue.Body = new TextMiner.TextCleaner.cleanTextASCIIRequestBody();
            inValue.Body.textStringBytesUTF8 = textStringBytesUTF8;
            TextMiner.TextCleaner.cleanTextASCIIResponse retVal = ((TextMiner.TextCleaner.TextCleaner)(this)).cleanTextASCII(inValue);
            return retVal.Body.cleanedTextASCII;
        }
    }
}
